name = "PowerLASCOPF"
uuid = "d47204b5-79de-42c6-9d37-20b6f7f5ad7f"
authors = ["Sambuddha Chakrabarti", "Mahdi Kefayati", "Ross Baldick"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
