# import all of the packages (and specific versions) needed
import Pkg
using Pkg
Pkg.add("IJulia")

# core packages
Pkg.add(Pkg.PackageSpec(name="BenchmarkTools"))
Pkg.add(Pkg.PackageSpec(name="CSV")) 
Pkg.add(Pkg.PackageSpec(name="DataFrames"))
Pkg.add(Pkg.PackageSpec(name="DataStructures"))
Pkg.add(Pkg.PackageSpec(name="Dates"))
Pkg.add(Pkg.PackageSpec(name="LinearAlgebra"))
Pkg.add(Pkg.PackageSpec(name="MathOptInterface"))
Pkg.add(Pkg.PackageSpec(name="MathProgBase"))
Pkg.add(Pkg.PackageSpec(name="RecursiveArrayTools"))
Pkg.add(Pkg.PackageSpec(name="Statistics"))
Pkg.add(Pkg.PackageSpec(name="StatsBase"))
Pkg.add(Pkg.PackageSpec(name="YAML"))
Pkg.add(Pkg.PackageSpec(name="Plots"))
Pkg.add(Pkg.PackageSpec(name="HydroPowerSimulations"))
Pkg.add(Pkg.PackageSpec(name="GeometryBasics"))
Pkg.add(Pkg.PackageSpec(name="PowerSystems", version= "4.4.1"))
Pkg.add(Pkg.PackageSpec(name="PowerSimulations", version = "0.29.1"))
Pkg.add(Pkg.PackageSpec(name="PowerGraphics"))
Pkg.add(Pkg.PackageSpec(name="PowerAnalytics"))
Pkg.add(Pkg.PackageSpec(name="Gurobi"))
Pkg.add(Pkg.PackageSpec(name="TimeSeries"))
Pkg.add(Pkg.PackageSpec(name="StorageSystemsSimulations"))
Pkg.add(Pkg.PackageSpec(name="GenX"))
Pkg.add(Pkg.PackageSpec(name="GLPK"))
Pkg.add(Pkg.PackageSpec(name="HiGHS"))
Pkg.add(Pkg.PackageSpec(name="Ipopt"))
Pkg.add(Pkg.PackageSpec(name="JuMP"))
Pkg.add(Pkg.PackageSpec(name="SCIP"))
Pkg.add(Pkg.PackageSpec(name="SparseArrays"))
Pkg.add(Pkg.PackageSpec(name="QUBO"))
Pkg.add(Pkg.PackageSpec(name="QuantumAnnealing"))
