import Pkg
using Pkg
Pkg.activate("JuMP_src")
#Pkg.add("Gurobi")
#Pkg.add("GLPK")
Pkg.add("MathOptInterfaceMosek")
#Pkg.add("MathOptInterface")
#Pkg.add("Cbc")
Pkg.add("Ipopt")
Pkg.add(name="Revise", version="3.1.5")
#Pkg.add(name="CSV", version="0.7.7")
Pkg.add(name="Cbc", version="0.7.1")
Pkg.add(name="Clp", version="0.8.1")
#Pkg.add(name="DataFrames", version="0.21.7")
Pkg.add(name="GLPK", version="0.13.0")
#Pkg.add(name="IJulia", version="1.21.3")
Pkg.add(name="JuMP", version="0.21.3")
Pkg.add(name="Plots", version="1.6.3")
Pkg.add(name="PrettyTables", version="0.9.1")
Pkg.add(name="SDDP", version="0.3.4")
Pkg.add(name="VegaLite", version="2.3.0")
Pkg.add(name="CPLEX", version="0.6.1")
Pkg.add(name="CSV", version="0.5.18")
Pkg.add(name="DataArrays", version="0.7.0")
Pkg.add(name="DataFrames", version="0.19.4")
Pkg.add(name="Gurobi", version="0.7.3")
Pkg.add(name="IJulia", version="1.20.2")
#Pkg.add(name="JuMP", version="0.18.6")
Pkg.add(name="Juno", version="0.7.2")
Pkg.add(name="MathOptFormat", version="0.2.2")
Pkg.add(name="MathOptInterface", version="0.9.7")
Pkg.add(name="MathProgBase", version="0.7.7")
Pkg.add(name="StatsBase", version="0.32.0")
Pkg.add(name="YAML", version="0.3.2")
Pkg.add(name="LinearAlgebra")
#Pkg.status()


